### ISSUE TITLE
network mirror mode // crashes on empty `platforms`

### ISSUE THREAD

**Issue by daniel-ciaglia** [boring-registry/boring-registry#196]
Hashicorp messed up the Terraform provider for aws `v5.71.0` multiple times

This time, their registry reports back empty platforms
relevant bug reports: https://github.com/hashicorp/terraform-provider-aws/issues/39706
```
curl -s https://registry.terraform.io/v1/providers/hashicorp/aws/versions | jq '.versions | .[] | select(.version == "5.71.0")' 
{
  "version": "5.71.0",
  "protocols": [
    "5.0"
  ],
  "platforms": []
}
```

vs. 

```
curl -s https://registry.terraform.io/v1/providers/hashicorp/aws/versions | jq '.versions | .[] | select(.version == "5.70.0")'
{
  "version": "5.70.0",
  "protocols": [
    "5.0"
  ],
  "platforms": [
    {
      "os": "linux",
      "arch": "arm"
    },
    {
      "os": "linux",
      "arch": "arm64"
    },
    {
      "os": "openbsd",
      "arch": "386"
    },
    {
      "os": "windows",
      "arch": "386"
    },
    {
      "os": "freebsd",
      "arch": "amd64"
    },
    {
      "os": "openbsd",
      "arch": "amd64"
    },
    {
      "os": "openbsd",
      "arch": "arm"
    },
    {
      "os": "linux",
      "arch": "amd64"
    },
    {
      "os": "linux",
      "arch": "386"
    },
    {
      "os": "freebsd",
      "arch": "arm"
    },
    {
      "os": "darwin",
      "arch": "amd64"
    },
    {
      "os": "freebsd",
      "arch": "386"
    },
    {
      "os": "windows",
      "arch": "amd64"
    },
    {
      "os": "darwin",
      "arch": "arm64"
    }
  ]
}
```

The boring registry does not expect this and happily crashes
```
{"time":"2024-10-14T08:04:33.687826782Z","level":"INFO","msg":"http: panic serving 10.16.1.185:58754: runtime error: invalid memory address or nil pointer dereference\ngoroutine 3796874 [running]:\nnet/http.(*conn).serve.func1()\n\t/usr/local/go/src/net/http/server.go:1898 +0xbe\npanic({0x1452660?, 0x2272120?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/boring-registry/boring-registry/pkg/mirror.loggingMiddleware.ListProviderInstallation.func1({0x2271330?, 0xc000b4c1c0?, 0x22babc0?})\n\t/go/src/github.com/boring-registry/boring-registry/pkg/mirror/middleware.go:64 +0x42f\npanic({0x15b3d00?, 0xc0001d4018?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/boring-registry/boring-registry/pkg/mirror.(*pullTroughMirror).upstreamSha256Sums(0xc000498150, {0x18be7e0, 0xc00071e780}, 0xc00046f340, 0xc0008fd038)\n\t/go/src/github.com/boring-registry/boring-registry/pkg/mirror/service.go:173 +0x245\ngithub.com/boring-registry/boring-registry/pkg/mirror.(*pullTroughMirror).ListProviderInstallation(0xc000498150, {0x18be7e0, 0xc00071e780}, 0xc00046f340)\n\t/go/src/github.com/boring-registry/boring-registry/pkg/mirror/service.go:120 +0x1a5\ngithub.com/boring-registry/boring-registry/pkg/mirror.loggingMiddleware.ListProviderInstallation({{0x18bc520?, 0xc000498150?}}, {0x18be7e0, 0xc00071e780}, 0xc00046f340)\n\t/go/src/github.com/boring-registry/boring-registry/pkg/mirror/middleware.go:67 +0x122\ngithub.com/boring-registry/boring-registry/pkg/mirror.MakeHandler.listProviderInstallationEndpoint.func6({0x18be7e0, 0xc00071e780}, {0x1577e80?, 0xc00081b080?})\n\t/go/src/github.com/boring-registry/boring-registry/pkg/mirror/endpoint.go:103 +0x3e4\ngithub.com/boring-registry/boring-registry/cmd.authMiddleware.Middleware.func1.1({0x18be7e0, 0xc00071e780}, {0x1577e80, 0xc00081b080})\n\t/go/src/github.com/boring-registry/boring-registry/pkg/auth/auth.go:32 +0x284\ngithub.com/go-kit/kit/transport/http.Server.ServeHTTP({0xc0003b4780, 0x16f42f8, 0x16f42f0, {0xc000400b20, 0x3, 0x4}, {0x0, 0x0, 0x0}, 0x16f3c50, ...}, ...)\n\t/go/src/github.com/boring-registry/boring-registry/vendor/github.com/go-kit/kit/transport/http/server.go:121 +0x337\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x7faa698aecf8?, 0xc000d6d5e0?}, 0xc0007207e0)\n\t/go/src/github.com/boring-registry/boring-registry/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:296 +0xcf\nnet/http.HandlerFunc.ServeHTTP(0x7faa698aecf8?, {0x7faa698aecf8?, 0xc000d6d5e0?}, 0x50?)\n\t/usr/local/go/src/net/http/server.go:2166 +0x29\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1({0x7faa698aecf8?, 0xc000d6d590?}, 0xc0007207e0)\n\t/go/src/github.com/boring-registry/boring-registry/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:243 +0xcf\nnet/http.HandlerFunc.ServeHTTP(0x7faa698aecf8?, {0x7faa698aecf8?, 0xc000d6d590?}, 0x7205a0?)\n\t/usr/local/go/src/net/http/server.go:2166 +0x29\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1({0x7faa698aecf8, 0xc000d6d540}, 0xc0007207e0)\n\t/go/src/github.com/boring-registry/boring-registry/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:97 +0xfd\nnet/http.HandlerFunc.ServeHTTP(0x18bc430?, {0x7faa698aecf8?, 0xc000d6d540?}, 0xc00071e210?)\n\t/usr/local/go/src/net/http/server.go:2166 +0x29\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x18bc430?, 0xc00046f260?}, 0xc0007207e0)\n\t/go/src/github.com/boring-registry/boring-registry/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:147 +0xc3\nnet/http.HandlerFunc.ServeHTTP(...)\n\t/usr/local/go/src/net/http/server.go:2166\nnet/http.HandlerFunc.ServeHTTP(0xc0007206c0?, {0x18bc430?, 0xc00046f260?}, 0x41a238?)\n\t/usr/local/go/src/net/http/server.go:2166 +0x29\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000486600, {0x18bc430, 0xc00046f260}, 0xc000720480)\n\t/go/src/github.com/boring-registry/boring-registry/vendor/github.com/gorilla/mux/mux.go:212 +0x1e2\ngithub.com/boring-registry/boring-registry/cmd.registerMirror.StripPrefix.func4({0x18bc430, 0xc00046f260}, 0xc000720360)\n\t/usr/local/go/src/net/http/server.go:2209 +0x262\nnet/http.HandlerFunc.ServeHTTP(0xc0000a41a0?, {0x18bc430?, 0xc00046f260?}, 0x7f315a?)\n\t/usr/local/go/src/net/http/server.go:2166 +0x29\nnet/http.(*ServeMux).ServeHTTP(0x4715f9?, {0x18bc430, 0xc00046f260}, 0xc000720360)\n\t/usr/local/go/src/net/http/server.go:2683 +0x1ad\nnet/http.serverHandler.ServeHTTP({0xc000c2db30?}, {0x18bc430?, 0xc00046f260?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:3137 +0x8e\nnet/http.(*conn).serve(0xc00090f710, {0x18be7e0, 0xc0000a82a0})\n\t/usr/local/go/src/net/http/server.go:2039 +0x5e8\ncreated by net/http.(*Server).Serve in goroutine 86\n\t/usr/local/go/src/net/http/server.go:3285 +0x4b4","hostname":"boring-registry-76ccb4998f-gxl9l"}
```

**Comment by odise** [comment]
https://github.com/boring-registry/boring-registry/pull/197 fixes the panic caused by the empty `platform` list.

**Comment by oliviermichaelis** [comment]
Thanks @odise @daniel-ciaglia for the report and quick fix! :heart: 

Version `v0.15.3` was released for the fix
